import { type Property } from '@/types/property';

const GALLERY_IMAGES = [
  'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=3840&q=90',
  'https://images.unsplash.com/photo-1600607687939-ce8a6d349c58?auto=format&fit=crop&w=3840&q=90',
  'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=3840&q=90',
  'https://images.unsplash.com/photo-1600607684527-6fb886090705?auto=format&fit=crop&w=3840&q=90',
] as const;

export const PROPERTIES: Property[] = [
  {
    slug: 'the-malabar-residences',
    title: 'The Malabar Residences',
    location: 'Calicut',
    district: 'Kozhikode',
    type: 'luxury',
    status: 'available',
    price: '₹2.4 Cr',
    priceNote: 'onwards',
    area: '3,200 sq ft',
    bedrooms: 4,
    bathrooms: 4,
    floors: 2,
    facing: 'East',
    possession: 'Ready to Move',
    year: '2024',
    heroImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'A contemporary masterpiece overlooking the Malabar coast, where modern design meets coastal serenity.',
    fullDescription: 'The Malabar Residences represent the pinnacle of coastal luxury in Calicut. Each residence is designed around light, air, and the unbroken horizon of the Arabian Sea. Floor-to-ceiling glass, cantilevered terraces, and materials sourced from across the subcontinent create spaces that feel both monumental and intimate. These are not just homes — they are addresses that define a generation.',
    amenities: ['Infinity Pool', 'Private Gym', 'Clubhouse', '24/7 Security', 'Landscaped Gardens', 'Concierge Service'],
    highlights: ['Panoramic Arabian Sea Views', 'Direct Beach Access', 'Sustainable Architecture', 'Smart Home Integration'],
    featured: true,
    collections: ['villas', 'luxury'],
  },
  {
    slug: 'seaward-villas',
    title: 'Seaward Villas',
    location: 'Kovalam',
    district: 'Trivandrum',
    type: 'villa',
    status: 'available',
    price: '₹1.8 Cr',
    priceNote: 'onwards',
    area: '2,800 sq ft',
    bedrooms: 3,
    bathrooms: 3,
    floors: 2,
    facing: 'West',
    possession: 'Ready to Move',
    year: '2023',
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Seaside villas in the heart of Kovalam, designed for those who seek stillness by the shore.',
    fullDescription: 'Seaward Villas occupy one of the most coveted stretches of coastline in Southern Kerala. Each villa draws from traditional Kerala architecture — sloped roofs, laterite walls, open courtyards — while integrating contemporary comforts seamlessly. The sound of the ocean is your constant companion. A place where time moves differently.',
    amenities: ['Private Deck', 'Landscaped Courtyard', 'Dedicated Parking', 'Beach Proximity'],
    highlights: ['Coastal Vernacular Design', 'Tranquil Beachside Setting', 'Premium Fixtures Throughout'],
    collections: ['villas', 'luxury'],
  },
  {
    slug: 'the-rosewood',
    title: 'The Rosewood',
    location: 'Kochi',
    district: 'Ernakulam',
    type: 'apartment',
    status: 'available',
    price: '₹1.2 Cr',
    area: '1,850 sq ft',
    bedrooms: 3,
    bathrooms: 3,
    floors: 14,
    facing: 'North',
    possession: '2025',
    year: '2025',
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Elegant urban living in the heart of Kochi, where convenience meets considered design.',
    fullDescription: 'The Rosewood is a residential landmark rising in the most connected neighbourhood of Kochi. Every apartment is a study in proportion — generous ceiling heights, cross-ventilated layouts, and finishes that age with grace. Below, the city pulses. Above, the sky stretches endlessly. This is what elevated living feels like.',
    amenities: ['Rooftop Garden', 'Sky Lounge', 'Indoor Games', 'High-speed Elevators', "Children's Play Area"],
    highlights: ['Central Kochi Location', 'Cross-ventilated Layouts', 'Premium Italian Flooring'],
    collections: ['apartments'],
  },
  {
    slug: 'palliyil-manor',
    title: 'Palliyil Manor',
    location: 'Thrissur',
    district: 'Thrissur',
    type: 'heritage',
    status: 'available',
    price: '₹3.5 Cr',
    area: '4,500 sq ft',
    landArea: '25 cents',
    bedrooms: 5,
    bathrooms: 5,
    floors: 2,
    facing: 'East',
    possession: 'Ready to Move',
    year: '1980',
    heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'A majestic heritage estate telling stories of a bygone era through its hand-carved wooden walls.',
    fullDescription: "Palliyil Manor is a testament to the grandeur of Kerala's architectural past. Built with ancient teak and laterite, the manor features a traditional Nalukettu design with a central courtyard that floods the home with natural light. Each room carries the patina of decades — polished wooden floors, carved doorways, brass fittings. Owning it is not an acquisition. It is a custodianship.",
    amenities: ['Traditional Nalukettu Courtyard', 'Ancient Well', 'Guest Wing', 'Extensive Lawns'],
    highlights: ['Heritage Architectural Status', 'Expansive 25-Cent Plot', 'Original Teak Woodwork'],
    collections: ['heritage'],
  },
  {
    slug: 'greenholm-terraces',
    title: 'Greenholm Terraces',
    location: 'Munnar',
    district: 'Idukki',
    type: 'villa',
    status: 'coming-soon',
    price: '₹2.2 Cr',
    area: '3,100 sq ft',
    bedrooms: 4,
    bathrooms: 4,
    floors: 2,
    facing: 'South',
    possession: '2026',
    year: '2026',
    heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6d349c58?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Terrace villas suspended among the mist-covered tea plantations of Munnar.',
    fullDescription: 'Greenholm Terraces are designed to disappear into the landscape. Each villa steps gently down the hillside, its green roof merging with the surrounding tea estates. Inside, double-height living spaces frame the valley like a painting. In the mornings, mist drifts through. In the evenings, the hills turn gold. This is not a home. It is a vantage point.',
    amenities: ['Panoramic Balconies', 'Heated Water Systems', 'Tea Garden Access', 'Mountain Trails'],
    highlights: ['Mist-filled Highland Setting', '360° Tea Estate Views', 'Biophilic Architecture'],
    collections: ['villas'],
  },
  {
    slug: 'the-lighthouse-apartments',
    title: 'The Lighthouse Apartments',
    location: 'Fort Kochi',
    district: 'Ernakulam',
    type: 'apartment',
    status: 'available',
    price: '₹95 L',
    area: '1,450 sq ft',
    bedrooms: 2,
    bathrooms: 2,
    floors: 6,
    facing: 'West',
    possession: 'Ready to Move',
    year: '2022',
    heroImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Boutique apartments inspired by the colonial charm and artistic pulse of Fort Kochi.',
    fullDescription: 'In a neighbourhood where Chinese fishing nets silhouette against the sunset and art galleries occupy centuries-old warehouses, The Lighthouse Apartments stand as a bridge between eras. Colonial proportions, contemporary finishes, and a rooftop that faces the harbour. Every evening here is a postcard you get to live inside.',
    amenities: ['Art Gallery Lobby', 'Harbour-facing Roof Deck', 'Bicycle Storage', 'High-speed Internet'],
    highlights: ['Heritage District Location', 'Walking Distance to Galleries', 'Sunset Harbour Views'],
    collections: ['apartments'],
  },
  {
    slug: 'varanda-estates',
    title: 'Varanda Estates',
    location: 'Alleppey',
    district: 'Alappuzha',
    type: 'plot',
    status: 'available',
    price: '₹45 L',
    priceNote: 'per cent',
    area: '12 cents',
    possession: 'Immediate',
    year: '2024',
    heroImage: 'https://images.unsplash.com/photo-1600607684527-6fb886090705?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Premium waterfront plots overlooking the serene backwaters of Alappuzha.',
    fullDescription: 'Varanda Estates is an invitation to build your dream on the water. These gated plots line the legendary backwaters of Alleppey — a landscape of coconut palms, houseboats, and silences that restore the soul. Infrastructure is in place. The canvas is ready. What you build here will become the story your family tells for generations.',
    amenities: ['Gated Community', 'Paved Internal Roads', 'Electricity & Water', 'Boat Jetty Access'],
    highlights: ['Direct Backwater Frontage', 'Clean Title Documentation', 'Architectural Advisory Included'],
    collections: ['plots'],
  },
  {
    slug: 'the-teakwood-bungalows',
    title: 'The Teakwood Bungalows',
    location: 'Wayanad',
    district: 'Wayanad',
    type: 'villa',
    status: 'available',
    price: '₹2.9 Cr',
    area: '3,800 sq ft',
    landArea: '15 cents',
    bedrooms: 4,
    bathrooms: 4,
    floors: 2,
    facing: 'East',
    possession: 'Ready to Move',
    year: '2024',
    heroImage: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Rustic luxury bungalows crafted from authentic teak and stone in the Wayanad highlands.',
    fullDescription: 'The Teakwood Bungalows are where architecture meets the forest. Built from sustainably sourced teak and local stone, each bungalow is a meditation on material and light. The forest canopy is your ceiling. The mountain air is your climate control. A fire pit under the stars, a coffee plantation at your doorstep, silence as a permanent resident.',
    amenities: ['Outdoor Fire Pit', 'Private Forest Trail', 'Yoga Deck', 'Organic Kitchen Garden'],
    highlights: ['Authentic Teak & Stone Construction', 'Complete Forest Immersion', '15-Cent Private Plot'],
    collections: ['villas', 'luxury'],
  },
  {
    slug: 'harbour-view',
    title: 'Harbour View',
    location: 'Kozhikode',
    district: 'Kozhikode',
    type: 'commercial',
    status: 'available',
    price: 'On Request',
    area: '12,000 sq ft',
    possession: 'Ready to Move',
    year: '2023',
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'A premium commercial landmark in Calicut designed for modern businesses and flagship retail.',
    fullDescription: 'Harbour View is not just a commercial space — it is a business address that commands attention. A glass-and-steel facade facing the Kozhikode harbour, column-free floor plates that adapt to any vision, and infrastructure built for the next decade. Whether you are opening a flagship store or establishing a corporate headquarters, this is where ambition finds its address.',
    amenities: ['Underground Parking', 'Central Air Conditioning', 'Full Glass Facade', 'Energy Efficient Systems'],
    highlights: ['Prime Harbour-facing Location', 'Column-free 12,000 sq ft Floor Plate', 'Grade-A Commercial Spec'],
    collections: ['commercial'],
  },
  {
    slug: 'the-hilltop-collection',
    title: 'The Hilltop Collection',
    location: 'Vagamon',
    district: 'Idukki',
    type: 'luxury',
    status: 'reserved',
    price: '₹3.8 Cr',
    area: '5,200 sq ft',
    landArea: '30 cents',
    bedrooms: 6,
    bathrooms: 6,
    floors: 3,
    facing: 'South-West',
    possession: 'Ready to Move',
    year: '2024',
    heroImage: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=3840&q=90',
    gallery: [...GALLERY_IMAGES],
    shortDescription: 'Ultra-luxury mansions perched on the highest ridgeline of Vagamon, limited to six residences.',
    fullDescription: "The Hilltop Collection is the rarest offering in our portfolio. Only six residences exist, each commanding a 30-cent plot on the Vagamon ridgeline. The views are 360 degrees — pine forests, meadows, valleys that stretch to the horizon. Every mansion is custom-designed to reflect its owner's vision. Private helipads, temperature-controlled wine cellars, and interiors by leading Kerala architects. This is not luxury. This is legacy.",
    amenities: ['Heated Infinity Pool', 'Private Helipad', 'Gourmet Kitchen', 'Wine Cellar', 'Home Theatre'],
    highlights: ['Only 6 Residences in Existence', 'Peak Ridgeline Position', 'Fully Bespoke Interiors'],
    collections: ['luxury', 'villas'],
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return PROPERTIES.find((p) => p.slug === slug);
}

export function getAllPropertySlugs(): string[] {
  return PROPERTIES.map((p) => p.slug);
}

export function getFeaturedProperties(): Property[] {
  return PROPERTIES.filter((p) => p.featured);
}

export function getPropertiesByType(type: string): Property[] {
  if (type === 'all') return PROPERTIES;
  return PROPERTIES.filter((p) => p.type === type);
}

export function getPropertiesByCollection(collection: string): Property[] {
  return PROPERTIES.filter((p) => p.collections?.includes(collection));
}
